from pathlib import Path


_filepath      = Path('include', 'auto_generated.ini')
_text_filepath = Path('include', 'auto_generated_text.txt')

def get_status():
    exists = _filepath.exists()
    enabled = False
    if exists:
        text = _filepath.read_text()
        enabled = len(text) > 0
    return exists, enabled

def clear():
    _filepath      .write_text('', encoding='utf-8')
    _text_filepath .write_text('', encoding='utf-8')

def generate(export_name, model_hashes, component_names):
    draw_content = '\n\n'.join([
        '\n'.join([
            '[TextureOverrideModel{}]'.format(i+1),
            'hash = {}'               .format(model_hash),
            '$active = 1',
            'match_priority = 0',
            'filter_index = 70111102111',
            'run = CommandListRT',
            'run = CommandListModel',
            'run = CommandListTexture',
        ])
        for i, model_hash in enumerate(model_hashes)
    ])

    with open(_filepath, 'w') as f:
        f.write(fixed_content)
        f.write(';------------TARGET MODEL----------\n')
        f.write(draw_content)
        f.write('\n\n\n')
        f.write(';-------------FILE END--------------\n')

    _text_filepath.write_text(
        '\n'.join([
            'Frame Analysis Targeting: {}'.format(export_name),
            *[
                '- {}  ({})'.format(model_hash, component_name)
                for model_hash, component_name in zip(model_hashes, component_names)
            ]
        ]),
        encoding='utf-8'
    )

fixed_content = '''
; AUTOGENERATED: DO NOT MANUALLY EDIT

[Constants]
global $active = 0

[Rendering]
dump_usage = 1

[Hunting]
hunting = 1
analyse_options =

[ShaderRegexEnableTargetedTextureOverrides]
shader_model = vs_4_0 vs_4_1 vs_5_0 vs_5_1
if !$costume_mods
    if ib == 70111102111
        checktextureoverride = ib
    endif
endif

;-------------INDICATOR-------------
[Present]
run = CommandListShowIndicator
post $active = 0

[CommandListShowIndicator]
pre Resource\\ShaderFixes\\help.ini\\Notification = ResourceText
if $active
    if !$costume_mods
        pre Resource\\ShaderFixes\\help.ini\\NotificationParams = ResourceIdealParams
    else
        pre Resource\\ShaderFixes\\help.ini\\NotificationParams = ResourceUsableParams
    endif
else
    pre Resource\\ShaderFixes\\help.ini\\NotificationParams = ResourceInactiveParams
endif
pre run = CustomShader\\ShaderFixes\\help.ini\\FormatText
pre $\\ShaderFixes\\help.ini\\notification_timeout = 0

[ResourceText]
type = Buffer
format = R8_UINT
filename = auto_generated_text.txt

[ResourceIdealParams]
type = StructuredBuffer
array = 1
data = R32_FLOAT  -0.99 -0 +1 +1   0 1.00 0.00 1   0 0 0 0.75   0.00 0.00   1 2   0   1.0

[ResourceUsableParams]
type = StructuredBuffer
array = 1
data = R32_FLOAT  -0.99 -0 +1 +1   0.80 0.80 0 1   0 0 0 0.75   0.00 0.00   1 2   0   1.0

[ResourceInactiveParams]
type = StructuredBuffer
array = 1
data = R32_FLOAT  -0.99 -0 +1 +1   1.00 0.00 0 1   0 0 0 0.75   0.00 0.00   1 2   0   1.0


;----------TARGET SHADERS-----------
[ShaderOverridePose]
; GI+HI Pose Shader One
hash = 653c63ba4a73ca8b
allow_duplicate_hash = overrule
analyse_options = dump_vb txt buf

[ShaderOverridePose1]
; ZZZ+SR Pose Shader One
hash = e8425f64cfb887cd
allow_duplicate_hash = overrule
analyse_options = dump_vb txt buf

[ShaderOverridePose2]
; ZZZ+SR Pose Shader Two
hash = a0b21a8e787c5a98
allow_duplicate_hash = overrule
analyse_options = dump_vb txt buf

[ShaderOverridePose3]
; ZZZ+SR Pose Shader Three
hash = 9684c4091fc9e35a
allow_duplicate_hash = overrule
analyse_options = dump_vb txt buf

[ShaderOverrideShapekey]
; ZZZ+SR ShapeKey Compute Shader
hash = 743108cc03f39cbf
allow_duplicate_hash = overrule
analyse_options = dump_rt dump_tex dump_cb buf txt

;----------PRESET COMMANDS----------
[CommandListModel]
analyse_options = dump_ib dump_vb txt buf

[CommandListRT]
analyse_options = dump_rt jps_dds

[CommandListTexture]
analyse_options = dump_tex


'''
